import "server-only";
import * as fs from "node:fs";
import * as path from "node:path";

/** Root of the published package, read from source like the demos. */
export const LIBRARY_ROOT = path.resolve(
  process.cwd(),
  "../../packages/base-ui",
);
export const LIBRARY_SRC = path.join(LIBRARY_ROOT, "src");

const GENERATED_MARKER = "// @generated by scripts/generate-exports.mjs";

/** Base UI entry points that are utilities, documented under /react/utils. */
const BASE_UI_UTILS = new Set([
  "csp-provider",
  "direction-provider",
  "merge-props",
  "unstable-use-media-query",
  "use-render",
]);

function readJson(file: string): { version: string } {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

export function getLibraryVersion(): string {
  return readJson(path.join(LIBRARY_ROOT, "package.json")).version;
}

export function getBaseUiVersion(): string {
  return readJson(
    path.join(LIBRARY_ROOT, "node_modules/@base-ui/react/package.json"),
  ).version;
}

export interface BaseUiEntry {
  slug: string;
  name: string;
  url: string;
  utility: boolean;
}

/** Entry points re-exported from Base UI by `generate-exports.mjs`. */
export function getBaseUiEntries(): BaseUiEntry[] {
  return fs
    .readdirSync(LIBRARY_SRC, { withFileTypes: true })
    .filter((dirent) => {
      const index = path.join(LIBRARY_SRC, dirent.name, "index.ts");
      return (
        dirent.isDirectory() &&
        dirent.name !== "types" &&
        fs.existsSync(index) &&
        fs.readFileSync(index, "utf8").startsWith(GENERATED_MARKER)
      );
    })
    .map((dirent) => {
      const utility = BASE_UI_UTILS.has(dirent.name);
      const slug = dirent.name.replace(/^unstable-/, "");
      return {
        slug: dirent.name,
        name: dirent.name
          .split("-")
          .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
          .join(" "),
        url: `https://base-ui.com/react/${utility ? "utils" : "components"}/${slug}`,
        utility,
      };
    });
}
