// Generates the Base UI re-export folders in `src/` and the `exports` map in
// `package.json`. Run it after adding a component or upgrading `@base-ui/react`:
// `pnpm generate:exports`.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = path.join(root, "src");
const packageJsonPath = path.join(root, "package.json");

// Marks files this script owns. Folders without it are our own components and
// are never overwritten, so a Base UI component can be replaced by our version.
const GENERATED_MARKER = "// @generated by scripts/generate-exports.mjs";

const baseUiPackageJson = JSON.parse(
  fs.readFileSync(
    path.join(root, "node_modules/@base-ui/react/package.json"),
    "utf8",
  ),
);

const baseUiEntries = Object.keys(baseUiPackageJson.exports)
  .filter((key) => key.startsWith("./") && key !== "./package.json")
  .filter((key) => !key.startsWith("./internals/"))
  .map((key) => key.slice(2));

for (const entry of baseUiEntries) {
  const dir = path.join(srcDir, entry);
  const file = path.join(dir, "index.ts");
  if (fs.existsSync(file)) {
    const content = fs.readFileSync(file, "utf8");
    if (!content.startsWith(GENERATED_MARKER)) continue;
  }
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(
    file,
    `${GENERATED_MARKER}\nexport * from "@base-ui/react/${entry}";\n`,
  );
}

const entries = fs
  .readdirSync(srcDir, { withFileTypes: true })
  .filter((dirent) => dirent.isDirectory())
  .map((dirent) => dirent.name)
  .filter((name) => fs.existsSync(path.join(srcDir, name, "index.ts")))
  .sort();

const exportsMap = {
  ".": { types: "./build/index.d.ts", default: "./build/index.js" },
};
for (const name of entries) {
  exportsMap[`./${name}`] = {
    types: `./build/${name}/index.d.ts`,
    default: `./build/${name}/index.js`,
  };
}
exportsMap["./package.json"] = "./package.json";

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
packageJson.exports = exportsMap;
fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);

console.log(
  `${baseUiEntries.length} Base UI entries, ${entries.length} exports written.`,
);
